# Rebind prefix:
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# switch panes with Alt-hjkl (Vim)
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
