# TPM plugins:
set -g @plugin 'tmux-plugins/tpm'

# Dracula theme plugin:
set -g @plugin 'dracula/tmux'
set -g @dracula-show-left-icon 󰌽
set -g @dracula-plugins "tmux-ram-usage"
set -g @dracula-show-powerline true

# TMUX navigator:
set -g @plugin 'christoomey/vim-tmux-navigator'

# TMUX resurrect:
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Rebind prefix:
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# ESC time-out
set -s escape-time 0

# Keybind for refresh config:
# unbind r
# bind r source-file ~./.tmux.conf

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Status bar top
set-option -g status-position top

# Enable TPM plugin manager
run '~/.tmux/plugins/tpm/tpm'
