opacity-rule = [
  "90:class_g = 'kitty'",
  "90:class_g = 'Org.gnome.Nautilus'",
  "90:class_g = 'thunderbird'"
];

blur:
{
  method = "dual_kawase";
  strength = 2;
}

backend = "glx";
glx-no-stencil = true;
